query EntryFilterQ(
  $limit: Int
  $offset: Int
  $dateFrom: DateMidnightUtc
  $dateTo: DateMidnightUtc
  $tags: [ObjectId!]
  $users: [ObjectId!]
  $self: Boolean
) {
  EntryFilterQ(
    limit: $limit
    offset: $offset
    dateFrom: $dateFrom
    dateTo: $dateTo
    tags: $tags
    users: $users
    self: $self
  ) {
    docs {
      id
      description
      deleted
      user {
        id
        username
      }
      date
      duration
      tags {
        id
        tagName
      }
    }
    hasMore
  }
}
