query DaySummariesQ(
  $dateFrom: DateMidnightUtc!
  $dateTo: DateMidnightUtc!
) {
  DaySummariesQ(
    dateFrom: $dateFrom
    dateTo: $dateTo
  ) {
    daySummaries {
      id
      date
      dayDuration
      projectSummaries {
        id
        name
        projectDuration
        portion
      }
    }
    maxDayDuration
  }
}
