query EntryFilterQ(
  $dateFrom: DateMidnightUtc
  $dateTo: DateMidnightUtc
  $limit: Int
  $offset: Int
  $self: Boolean
  $order: OrderI
  $project: Int
  $tags: [Int!]
  $users: [Int!]
  ) {
  EntryFilterQ(
    dateFrom: $dateFrom
    dateTo: $dateTo
    limit: $limit
    offset: $offset
    self: $self
    order: $order
    tags: $tags
    project: $project
    users: $users
  ) {
  docs {
    ... on Entry {
      createdAt
      date
      description
      duration
      id
      project {
        id,
        projectName
      }
      tags {
        id
        tagName
      }
      user {
        id
        username
      }
    }
  }
  hasMore
  }
}
