query EntryFilterQ(
  $dateFrom: DateMidnightUtc
  $dateTo: DateMidnightUtc
  $limit: Int
  $offset: Int
  $order: OrderI
  $projects: [ProjectI]
  $tags: [TagI]
  $users: [UserI]
  ) {
  EntryFilterQ(
    dateFrom: $dateFrom
    dateTo: $dateTo
    limit: $limit
    offset: $offset
    order: $order
    projects: $projects
    tags: $tags
    users: $users
  ) {
  docs {
    ... on Entry {
      createdAt
      date
      description
      duration
      id
      project {
        id,
        name
      }
      tags {
        id
        name
      }
      user {
        id
        name
        gravatar
      }
    }
  }
  hasMore
  }
}
