query TagPartialQ(
  $tagPartial: String
  $limit: Int
  $offset: Int
  $includeArchived: Boolean
) {
  TagPartialQ(
    tagPartial: $tagPartial
    limit: $limit
    offset: $offset
    includeArchived: $includeArchived
  ) {
    docs {
      ... on Tag {
        id
        name
        archived
      }
    }
    hasMore
  }
}
